export const oil = [
	{
		id: 1,
        src: "./images/oil/oil_monini_1l.jpg",
		alt: "oil_monini_1l",
		title: "Оливкова олія Monini Classico (Італія)",
		description: "Оливкова олія першого холодного віджиму Monini Classico",
		measure: "1 л",
		price: 380,
		category: "oil",
	},
	{
		id: 2,
        src: "./images/oil/oil_monini.jpg",
		alt: "oil_monini",
		title: "Оливкова олія Monini Extra Vergine Classico",
		description: "Олія оливкова Monini - класичний смак оливкового масла",
		measure: "1 л",
		price: 150,
		category: "oil",
	},
	{
		id: 3,
        src: "./images/oil/oil_dececco.jpg",
		alt: "oil_dececco",
		title: "Оливкова олія De Cecco Extra Vergine Classico (Греція)",
		description: "Олія першого холодного віджиму, висока якість якого визначається його золотавим кольором",
		measure: "1 л",
		price: 150,
		category: "oil",
	},
	{
		id: 4,
        src: "./images/oil/oil_dececco_1l.jpg",
		alt: "oil_dececco",
		title: "Оливкова олія De Cecco Classico Extra Virgin (Італія)",
		description: "Оливкова олія De Cecco Classico Extra Virgin, нерафінована",
		measure: "1 л",
		price: 330,
		category: "oil",
	},
	{
		id: 5,
        src: "./images/oil/oil_olio.jpg",
		alt: "oil_olio",
		title: "Оливкова олія Olio extra vergine di oliva",
		description: "Оливкова олія першого холодного віджиму. Чистий запах оливок з відтінком трав'яних тонів",
		measure: "1 л",
		price: 150,
		category: "oil",
	},
	{
		id: 6,
        src: "./images/oil/ris_basmati.jpg",
		alt: "ris_basmati",
		title: "Рис басматі (подвійна пропарка)",
		description: "Зерна довші та тонші від звичайного рису, а під час варіння вони ще більше подовжуються",
		measure: "1 кг",
		price: 150,
		category: "oil",
	},
	{
		id: 7,
        src: "./images/oil/ris_basmati_5.jpg",
		alt: "ris_basmati_5",
		title: "Рис басматі",
		description: "Для цього сорту рису найбільше підходить метод варіння під кришкою або на пару",
		measure: "5 кг",
		price: 590,
		category: "oil",
	},
	{
		id: 8,
        src: "./images/oil/oil_mix.jpg",
		alt: "oil_mix",
		title: "Оливкова олія",
		description: "Оливкова олія",
		measure: "1 л",
		price: 150,
		category: "oil",
	},
	{
		id: 9,
        src: "./images/oil/oil_5l.jpg",
		alt: "oil_5l",
		title: "Оливкова олія",
		description: "Оливкова олія",
		measure: "5 л",
		price: 420,
		category: "oil",
	},
];
