export const candy = [
	{
		id: 1,
        src: "./images/candy/pahlava_gorih.jpg",
		alt: "pahlava_gorih",
		title: "Пахлава SULTAN з волоським горіхом (Туреччина)",
		description: "Пахлаву готують з безлічі листів тіста завтовшки трохи більше 1 мм",
		measure: "1 кг",
		price: 250,
		category: "candy",
	},
	{
		id: 2,
        src: "./images/candy/pahlava_fistashka.jpg",
		alt: "pahlava_fistashka",
		title: "Пахлава з фісташкою SULTAN (Туреччина)",
		description: "Пахлаву готують із безлічі листів тіста завтовшки трохи більше 1 мм",
		measure: "1 кг",
		price: 280,
		category: "candy",
	},
	{
		id: 3,
        src: "./images/candy/halva_molochna.jpg",
		alt: "halva_molochna",
		title: "Халва самаркандська, узбецька, молочна",
		description: "Халва — східна солодкість з збитою з піноутворювачем карамельної маси",
		measure: "500 г",
		price: 90,
		category: "candy",
	},
	{
		id: 4,
        src: "./images/candy/halva_mramor.jpg",
		alt: "halva_mramor",
		title: "Халва самаркандська, узбецька, мрамор",
		description: "Халва — східна солодкість з збитою з піноутворювачем карамельної маси",
		measure: "500 г",
		price: 90,
		category: "candy",
	},
	{
		id: 5,
        src: "./images/candy/candy_finik.jpg",
		alt: "candy_finik",
		title: "Цукерки Amanti Фінік с грецким орехом",
		description: "Цукерки Amanti Фінік с грецким орехом",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 6,
        src: "./images/candy/candy_grysha.jpg",
		alt: "candy_grysha",
		title: "Цукерки Amanti Груша з волоським горіхом",
		description: "Цукерки Amanti Груша з волоським горіхом",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 7,
        src: "./images/candy/sgyshenka_1000.jpg",
		alt: "sgyshenka_1000",
		title: "Згущене молоко Leche Condensada Benestare (Іспанія)",
		description: "Тахітна халва є дуже смачним і поживним продуктом",
		measure: "1 л",
		price: 220,
		category: "candy",
	},
	{
		id: 8,
        src: "./images/candy/halva_t.jpg",
		alt: "halva_t",
		title: "Халва Тахінна",
		description: "Виготовлено з цільного молока",
		measure: "1 кг",
		price: 220,
		category: "candy",
	},
	{
		id: 8.5,
        src: "./images/candy/halva_f.jpg",
		alt: "halva_f",
		title: "Халва Тахінна з фісташками",
		description: "Виготовлено з цільного молока",
		measure: "400 г",
		price: 170,
		category: "candy",
	},
	{
		id: 9,
        src: "./images/candy/pismaniye.jpg",
		alt: "pismaniye",
		title: "Пішманіє (легка халва) фісташка, ваніль, тахіні",
		description: "Являє собою клубки з тонких ниток, що складаються з обсмажених в олії, борошні та цукрі",
		measure: "240 г",
		price: 160,
		category: "candy",
	},
	{
		id: 10,
        src: "./images/candy/pahlava_perska.jpg",
		alt: "pahlava_perska",
		title: "Пахлава перська",
		description: "Пахлава Перська з фісташкою SULTAN 400г - пахлаву готують з безлічі листів тіста завтовшки не більше 1 мм",
		measure: "400 г",
		price: 140,
		category: "candy",
	},
	{
		id: 11,
        src: "./images/candy/nutella.jpg",
		alt: "nutella",
		title: "Nutella (Німеччина)",
		description: "Величезна шоколадно-горіхова паста Nutella",
		measure: "1 кг",
		price: 350,
		category: "candy",
	},
	{
		id: 12,
        src: "./images/candy/pahlava_perska_fistashka.jpg",
		alt: "pahlava_perska_fistashka",
		title: "Пахлава перська із фісташкою",
		description: "Пахлава Перська з фісташкою SULTAN 400 г",
		measure: "400 г",
		price: 190,
		category: "candy",
	},
	{
		id: 13,
        src: "./images/candy/pahlava_perska_gorih.jpg",
		alt: "pahlava_perska_gorih",
		title: "Пахлава перська з волоським горіхом",
		description: "Пахлава Перська з фісташкою SULTAN 400 г",
		measure: "400 г",
		price: 140,
		category: "candy",
	},
	{
		id: 14,
        src: "./images/candy/candy_pinakolada.jpg",
		alt: "candy_pinakolada",
		title: "Цукерки Amanti Піна Колада",
		description: "Цукерки Amanti Піна Колада, кокос плюс ананас",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 15,
        src: "./images/candy/candy_meteorit.jpg",
		alt: "candy_meteorit",
		title: "Цукерки Amanti Метеорит",
		description: "Цукерки Amanti Метеорит",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 16,
        src: "./images/candy/candy_grilag.jpg",
		alt: "candy_grilag",
		title: "Цукерки Amanti Грільяж",
		description: "Цукерки Amanti Грільяж, арахіс плюс журавлина",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 17,
        src: "./images/candy/candy_prometei.jpg",
		alt: "candy_prometei",
		title: "Цукерки Amanti Східний Прометей",
		description: "Цукерки Amanti Східний Прометей, з родзинками",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 18,
        src: "./images/candy/candy_chornosliv_gorih.jpg",
		alt: "candy_chornosliv_gorih",
		title: "Цукерки Amanti Чорнослив",
		description: "Цукерки Amanti Чорнослив, з волоським горіхом",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 19,
        src: "./images/candy/candy_moxito.jpg",
		alt: "candy_moxito",
		title: "Цукерки Amanti Мoxito",
		description: "Цукерки Amanti Мoxito",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 20,
        src: "./images/candy/candy_bayntino.jpg",
		alt: "candy_bayntino",
		title: "Цукерки Amanti Баунтіно Кокос",
		description: "Цукерки Amanti Баунтіно Кокос",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 21,
        src: "./images/candy/candy_chornosliv_migdal.jpg",
		alt: "candy_chornosliv_migdal",
		title: "Цукерки Amanti Чорнослив",
		description: "Цукерки Amanti Чорнослив, з мигдалем",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 22,
        src: "./images/candy/candy_chornosliv_glazyr.jpg",
		alt: "candy_chornosliv_glazyr",
		title: "Цукерки Amanti Чорнослив",
		description: "Цукерки Amanti Чорнослив, в глазурі",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 23,
        src: "./images/candy/candy_klybnika.jpg",
		alt: "candy_klybnika",
		title: "Цукерки Amanti Чорнослив",
		description: "Цукерки Amanti Чорнослив, полуничний мікс",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 24,
        src: "./images/candy/candy_vishna.jpg",
		alt: "candy_vishna",
		title: "Цукерки Amsnti Вишня коктейль",
		description: "Цукерки Amsnti Вишня коктейль",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
	{
		id: 25,
        src: "./images/candy/halva_tahina.jpg",
		alt: "halva_tahina",
		title: "Халва тахінна з Фісташками",
		description: "Халва тахінна з Фісташками",
		measure: "350 г",
		price: 170,
		category: "candy",
	},
	{
		id: 26,
        src: "./images/candy/arahis.jpg",
		alt: "arahis",
		title: "Арахіс у глазурі",
		description: "Арахіс у глазурі",
		measure: "1 кг",
		price: 240,
		category: "candy",
	},
	{
		id: 27,
        src: "./images/candy/rodzinki.jpg",
		alt: "rodzinki",
		title: "Родзинки в глазурі",
		description: "Родзинки в глазурі",
		measure: "1 кг",
		price: 240,
		category: "candy",
	},
	{
		id: 28,
        src: "./images/candy/keshu.jpg",
		alt: "keshu",
		title: "Кеш'ю у шоколаді",
		description: "Кеш'ю у шоколаді",
		measure: "1 кг",
		price: 340,
		category: "candy",
	},
	{
		id: 29,
        src: "./images/candy/fyndyk.jpg",
		alt: "fyndyk",
		title: "Фундук у шоколаді",
		description: "Фундук у шоколаді",
		measure: "1 кг",
		price: 340,
		category: "candy",
	},
	{
		id: 30,
        src: "./images/candy/migdal.jpg",
		alt: "migdal",
		title: "Мигдаль у шоколаді",
		description: "Мигдаль у шоколаді",
		measure: "1 кг",
		price: 340,
		category: "candy",
	},
	{
		id: 31,
        src: "./images/candy/pishmanie_asorti.jpg",
		alt: "pishmanie_asorti",
		title: "Пішманіє",
		description: "Пішманіє — легка халва, смакота турецької кухні",
		measure: "240 г",
		price: 160,
		category: "candy",
	},
	{
		id: 32,
        src: "./images/candy/candy_perfetto.jpg",
		alt: "candy_perfetto",
		title: "Цукерки Перфетто",
		description: "Цукерки Перфетто",
		measure: "500 г",
		price: 150,
		category: "candy",
	},
	{
		id: 33,
        src: "./images/candy/halva_tahina_350.jpg",
		alt: "halva_tahina_350",
		title: "Халва Тахітна",
		description: "Тахітна халва є дуже смачним і поживним продуктом",
		measure: "350 г",
		price: 170,
		category: "candy",
	},
	{
		id: 34,
        src: "./images/candy/halva_tahina_fistashka.jpg",
		alt: "halva_tahina_fistashka",
		title: "Халва Тахітна фисташкова",
		description: "Тахітна халва є дуже смачним і поживним продуктом",
		measure: "350 г",
		price: 170,
		category: "candy",
	},
	{
		id: 35,
        src: "./images/candy/halva_tahina_1.jpg",
		alt: "halva_tahina_1",
		title: "Халва Тахітна",
		description: "Тахітна халва є дуже смачним і поживним продуктом",
		measure: "350 г",
		price: 150,
		category: "candy",
	},
	{
		id: 36,
        src: "./images/candy/fruit_pasta.jpg",
		alt: "fruit_pasta",
		title: "Фруктова пастила",
		description: "Фруктова пастила",
		measure: "25 шт",
		price: 300,
		category: "candy",
	},
	{
		id: 37,
        src: "./images/candy/kazinaki.jpg",
		alt: "kazinaki",
		title: "Казінаки",
		description: "Склад: насіння соняшнику, цукор, кунжут",
		measure: "1 кг",
		price: 180,
		category: "candy",
	},
	{
		id: 38,
        src: "./images/candy/halva_fistashka.jpg",
		alt: "halva_fistashka",
		title: "Халва Турецька фісташкова",
		description: "Халва Турецька фісташкова",
		measure: "400 г",
		price: 220,
		category: "candy",
	},
	{
		id: 39,
        src: "./images/candy/chychhela.jpg",
		alt: "chychhela",
		title: "Чурчхела асорті",
		description: "Чурчхела асорті (ваговий, від 500г)<br>- горіх світлий виноград<br>- горіх темний виноград<br>- горіх гранат",
		measure: "1 кг",
		price: 370,
		category: "candy",
	},
	{
		id: 40,
        src: "./images/candy/pahlava_gorih_volos.jpg",
		alt: "pahlava_gorih_volos",
		title: "Пахлава з волоським горіхом",
		description: "Пахлаву готують із безлічі листів тіста і завтовшки трохи більше 1 мм",
		measure: "1 кг",
		price: 190,
		category: "candy",
	},
	{
		id: 41,
        src: "./images/candy/candy_asorti.jpg",
		alt: "candy_asorti",
		title: "Цукерки асорті Аманті",
		description: "Склад: чорнослив, курага, грильяжі, метеорит, прометей, смородина, кокос, вишня, фінік",
		measure: "1 кг",
		price: 230,
		category: "candy",
	},
];
