export const rahat = [
	{
		id: 1,
        src: "./images/rahat/rahat_1.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "1,5 кг",
		price: 200,
		category: "rahat",
	},
	{
		id: 2,
        src: "./images/rahat/rahat_2.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "1,5 кг",
		price: 210,
		category: "rahat",
	},
	{
		id: 3,
        src: "./images/rahat/rahat_3.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "1,5 кг",
		price: 210,
		category: "rahat",
	},
	{
		id: 4,
        src: "./images/rahat/rahat_4.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "1,5 кг",
		price: 210,
		category: "rahat",
	},
	{
		id: 5,
        src: "./images/rahat/rahat_5.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "1,5 кг",
		price: 210,
		category: "rahat",
	},
	{
		id: 6,
        src: "./images/rahat/rahat_6.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "500 г",
		price: 355,
		category: "rahat",
	},
	{
		id: 7,
        src: "./images/rahat/rahat_7.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум, з горіхом",
		measure: "1,5 кг",
		price: 210,
		category: "rahat",
	},
	{
		id: 8,
        src: "./images/rahat/rahat_8.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум, з горіхом",
		measure: "2 кг",
		price: 250,
		category: "rahat",
	},
	{
		id: 9,
        src: "./images/rahat/rahat_9.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум - це давня східна насолода. Складається з фруктового соку, крохмалю, цукру та арахісу.<br>Смак граната, абрикос, ківі та ванілі",
		measure: "1,5 кг",
		price: 200,
		category: "rahat",
	},
	{
		id: 10,
        src: "./images/rahat/rahat_10.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "500 г",
		price: 355,
		category: "rahat",
	},
	{
		id: 11,
        src: "./images/rahat/rahat_11.jpg",
		alt: "rahat",
		title: "Рахат-Лукум (Турецький)",
		description: "В наборі 4 види: Мигдаль, Фісташка, Фісташка з гранатом, Барбарис",
		measure: "350 г",
		price: 240,
		category: "rahat",
	},
	{
		id: 12,
        src: "./images/rahat/rahat_12.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум, фруктовий",
		measure: "1,5 кг",
		price: 190,
		category: "rahat",
	},
	{
		id: 13,
        src: "./images/rahat/rahat_13.jpg",
		alt: "rahat",
		title: "Рахат-лукум Turkish Delight Premium Sultan",
		description: "Три види Атом (фісташка, барбарис, мигдальні пластівці), два види Мега (фісташка, мигдаль",
		measure: "200 г",
		price: 110,
		category: "rahat",
	},
	{
		id: 14,
        src: "./images/rahat/rahat_14.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум, турецький, асорті",
		measure: " 750 г",
		price: 395,
		category: "rahat",
	},
	{
		id: 15,
        src: "./images/rahat/rahat_15.jpg",
		alt: "rahat",
		title: "Рахат-Лукум, турецький",
		description: "- горіхова паста та фісташки<br>- горіхова паста та мигдаль<br>- фісташка та вишня<br>- горіхова паста та шоколад",
		measure: "300 г",
		price: 170,
		category: "rahat",
	},
];
