export const gorikhi = [
	{
		id: 1,
        src: "./images/gorikhi/mindal.jpg",
		alt: "mindal",
		title: "Миндаль у скорлупі",
		description: "Миндаль у скорлупі смажений<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 450,
		category: "gorikhi",
	},
	{
		id: 2,
        src: "./images/gorikhi/mix.jpg",
		alt: "mix",
		title: "МІКС горіхи + сухофрукти",
		description: "Склад: ізюм синій, ізюм золотий, цукати кубики, кеш'ю, фундук, мигдаль золотий<br>(Горіхи не смажені)",
		measure: "500 г",
		price: 200,
		category: "gorikhi",
	},
	{
		id: 3,
        src: "./images/gorikhi/keshy.jpg",
		alt: "keshy",
		title: "Кеш'ю сирий (В'єтнам)",
		description: "Кеш'ю сирий<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 460,
		category: "gorikhi",
	},
	{
		id: 4,
        src: "./images/gorikhi/migdal.jpg",
		alt: "migdal",
		title: "Мигдаль золотий, сирий (Америка)",
		description: "Мигдаль золотий, сирий<br>(ваговий, від 500г)",
		measure: "1 кг",
		price: 430,
		category: "gorikhi",
	},
	{
		id: 5,
        src: "./images/gorikhi/fistashka.jpg",
		alt: "fistashka",
		title: "Фісташки, смажені (США)",
		description: "Фісташки смажені<br>(вагові, від 500г)",
		measure: "1 кг",
		price: 590,
		category: "gorikhi",
	},
	{
		id: 6,
        src: "./images/gorikhi/pekan.jpg",
		alt: "pekan",
		title: "Пекан в шкаралупі",
		description: "Пекан в шкаралупі",
		measure: "500 г",
		price: 500,
		category: "gorikhi",
	},
	{
		id: 7,
        src: "./images/gorikhi/pekan_karamel.jpg",
		alt: "pekan_karamel",
		title: "Пекан карамельний горіх (Америка)",
		description: "Пекан карамельний горіх, чищений",
		measure: "500 г",
		price: 550,
		category: "gorikhi",
	},
	{
		id: 8,
        src: "./images/gorikhi/makadamia.jpg",
		alt: "makadamia",
		title: "Макадамія",
		description: "Макадамія – король серед горіхів. Це криниця цінних поживних речовин",
		measure: "250 г",
		price: 125,
		category: "gorikhi",
	},
	{
		id: 8.5,
        src: "./images/gorikhi/makadamia.jpg",
		alt: "makadamia",
		title: "Макадамія",
		description: "Макадамія – король серед горіхів. Це криниця цінних поживних речовин",
		measure: "500 г",
		price: 250,
		category: "gorikhi",
	},
	{
		id: 9,
        src: "./images/gorikhi/fistashki_alesto.jpg",
		alt: "fistashki_alesto",
		title: "Фісташки Alesto",
		description: "Фісташки Alesto – це добірні, смажені та підсолені горішки. Каліфорнійський сорт відрізняється великими розмірами",
		measure: "250 г",
		price: 180,
		category: "gorikhi",
	},
	{
		id: 10,
        src: "./images/gorikhi/fistashki_alesto.jpg",
		alt: "fistashki_alesto",
		title: "Фісташки Alesto",
		description: "Фісташки Alesto – це добірні, смажені та підсолені горішки. Каліфорнійський сорт відрізняється великими розмірами",
		measure: "500 г",
		price: 320,
		category: "gorikhi",
	},
	{
		id: 11,
        src: "./images/gorikhi/kedr.jpg",
		alt: "kedr",
		title: "Кедровий горіх",
		description: "Кедровий горіх<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 1300,
		category: "gorikhi",
	},
	{
		id: 12,
        src: "./images/gorikhi/oreh_mix.jpg",
		alt: "oreh_mix",
		title: "МІКС горішків",
		description: "В набір входить: кеш'ю, фундук, мигдаль",
		measure: "500 г",
		price: 240,
		category: "gorikhi",
	},
	{
		id: 13,
        src: "./images/gorikhi/fyndyk_blansh.jpg",
		alt: "fyndyk_blansh",
		title: "Фундук Бланш (Туреччина)",
		description: "Фундук Бланш<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 450,
		category: "gorikhi",
	},
];
