export const sukhofrukty = [
	{
		id: 1,
        src: "./images/sukhofrukty/mango_suwene.jpg",
		alt: "mango_suwene",
		title: "Манго сушене",
		description: "Манго сушене ТМ 7000 Natural без цукру",
		measure: "500 г",
		price: 250,
		category: "sukhofrukty",
	},
	{
		id: 2,
        src: "./images/sukhofrukty/chornosliv.jpg",
		alt: "chornosliv",
		title: "Чорнослив в'ялений (Україна)",
		description: "Чорнослив в'ялений крупний без кісточки<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 220,
		category: "sukhofrukty",
	},
	{
		id: 3,
        src: "./images/sukhofrukty/chornosliv.jpg",
		alt: "chornosliv",
		title: "Чорнослив копчений (Україна)",
		description: "Чорнослив копчений без кісточки<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 150,
		category: "sukhofrukty",
	},
	{
		id: 4,
        src: "./images/sukhofrukty/mango_royal.jpg",
		alt: "mango_royal",
		title: "Манго натуральний ROYAL",
		description: "Манго натуральний ROYAL",
		measure: "250 г",
		price: 150,
		category: "sukhofrukty",
	},
	{
		id: 5,
        src: "./images/sukhofrukty/kyraga_shokolad.jpg",
		alt: "kyraga_shokolad",
		title: "Курага шоколад",
		description: "Курага натуральна, шоколад<br>(вагова)",
		measure: "1 кг",
		price: 470,
		category: "sukhofrukty",
	},
	{
		id: 6,
        src: "./images/sukhofrukty/klukva.jpg",
		alt: "klukva",
		title: "Клюква сушена",
		description: "Клюква сушена<br>(вагова, від 500 г)",
		measure: "1 кг",
		price: 380,
		category: "sukhofrukty",
	},
	{
		id: 7,
        src: "./images/sukhofrukty/kivi.jpg",
		alt: "kivi",
		title: "Ківі сушений (Тайланд)",
		description: "Ківі сушений цукат<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 280,
		category: "sukhofrukty",
	},
	{
		id: 8,
        src: "./images/sukhofrukty/finiki.jpg",
		alt: "finiki",
		title: "Фініки Salammbo (Туніс)",
		description: "Фініки Salammbo",
		measure: "1 кг",
		price: 170,
		category: "sukhofrukty",
	},
	{
		id: 9,
        src: "./images/sukhofrukty/cukati.jpg",
		alt: "cukati",
		title: "Цукати кубики (Китай)",
		description: "Цукати кубики 8-10 мм<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 250,
		category: "sukhofrukty",
	},
	{
		id: 10,
        src: "./images/sukhofrukty/kyraga_industrial.jpg",
		alt: "kyraga_industrial",
		title: "Курага ІНДУСТРІАЛ (Туреччина)",
		description: "Курага ІНДУСТРІАЛ<br>(вагова, від 500 г)",
		measure: "1 кг",
		price: 320,
		category: "sukhofrukty",
	},
	{
		id: 11,
        src: "./images/sukhofrukty/izum_zolotij.jpg",
		alt: "izum_zolotij",
		title: "Ізюм золотий (УЗБЕКИСТАН)",
		description: "Ізюм золотий<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 190,
		category: "sukhofrukty",
	},
	{
		id: 12,
        src: "./images/sukhofrukty/izum_sinij.jpg",
		alt: "izum_sinij",
		title: "Ізюм синій (УЗБЕКИСТАН)",
		description: "Ізюм синій<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 240,
		category: "sukhofrukty",
	},
	{
		id: 13,
        src: "./images/sukhofrukty/kyraga_jambo.jpg",
		alt: "kyraga_jambo",
		title: "Курага ДЖАМБО DJ (Турция)",
		description: "Курага ДЖАМБО DJ<br>(вагова, від 500 г)",
		measure: "1 кг",
		price: 460,
		category: "sukhofrukty",
	},
	{
		id: 14,
        src: "./images/sukhofrukty/vishna_krasna.jpg",
		alt: "vishna_krasna",
		title: "Вишня червона",
		description: "Вишня червона, в'ялена<br>(вагова, від 500 г)",
		measure: "1 кг",
		price: 430,
		category: "sukhofrukty",
	},
	{
		id: 15,
        src: "./images/sukhofrukty/izum_palchik.jpg",
		alt: "izum_palchik",
		title: "Ізюм дамський пальчик",
		description: "Узбекський ізюм дамський пальчик, золотий<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 350,
		category: "sukhofrukty",
	},
	{
		id: 16,
        src: "./images/sukhofrukty/ananas_kolco.jpg",
		alt: "ananas_kolco",
		title: "Кільця ананасу сушені",
		description: "Кільця ананасу сушені без додавання цукру. Сушений ананас – поживна та здорова ідея для перекушування",
		measure: "500 г",
		price: 230,
		category: "sukhofrukty",
	},
	{
		id: 17,
        src: "./images/sukhofrukty/dina.jpg",
		alt: "dina",
		title: "Диня сушена",
		description: "Диня сушена Канталупа Holland Fruit",
		measure: "500 г",
		price: 250,
		category: "sukhofrukty",
	},
	{
		id: 18,
        src: "./images/sukhofrukty/ingir.jpg",
		alt: "ingir",
		title: "Інжир сушений 1111 Brothers (Туреччина)",
		description: "Сушений інжир найвищої якості та 100% натуральний. Інжир цінується за м’який, солодкий смак",
		measure: "200 г",
		price: 65,
		category: "sukhofrukty",
	},
	{
		id: 19,
        src: "./images/sukhofrukty/mango_holland.jpg",
		alt: "mango_holland",
		title: "Манго Holland Fruit, сушений без цукру",
		description: "Манго сушений Holland Fruit – це смачний і корисний продукт, 500 г",
		measure: "500 г",
		price: 230,
		category: "sukhofrukty",
	},
	{
		id: 19/1,
        src: "./images/sukhofrukty/mango_holland.jpg",
		alt: "mango_holland",
		title: "Манго Holland Fruit, сушений без цукру",
		description: "Манго сушений Holland Fruit – це смачний і корисний продукт, 500 г",
		measure: "250 г",
		price: 140,
		category: "sukhofrukty",
	},
	{
		id: 20,
        src: "./images/sukhofrukty/cukati_ananas.jpg",
		alt: "cukati_ananas",
		title: "Ананас кубики цукат",
		description: "Ананас кубики цукат",
		measure: "500 г",
		price: 125,
		category: "sukhofrukty",
	},
	{
		id: 21,
        src: "./images/sukhofrukty/ingir_vaga.jpg",
		alt: "ingir_vaga",
		title: "Інжир TESCO",
		description: "Інжир TESCO<br>(ваговий)",
		measure: "1 кг",
		price: 240,
		category: "sukhofrukty",
	},
	{
		id: 22,
        src: "./images/sukhofrukty/mango_cykor.jpg",
		alt: "mango_cykor",
		title: "Манго з цукром",
		description: "Манго з цукром",
		measure: "1 кг",
		price: 210,
		category: "sukhofrukty",
	},
	{
		id: 23,
        src: "./images/sukhofrukty/mango_suwene_1.jpg",
		alt: "mango_suwene_1",
		title: "Манго сушене",
		description: "Манго сушене",
		measure: "250 г",
		price: 150,
		category: "sukhofrukty",
	},
	{
		id: 24,
        src: "./images/sukhofrukty/finiki_natyralni.jpg",
		alt: "finiki_natyralni",
		title: "Фініки натуральні",
		description: "Фініки натуральні",
		measure: "130 г",
		price: 550,
		category: "sukhofrukty",
	},
	{
		id: 25,
        src: "./images/sukhofrukty/finiki_mazafati.jpg",
		alt: "finiki_mazafati",
		title: "Фініки Mazafati",
		description: "Натуральні фініки, без олії та сиропу. Зовні сухі, дуже м'які всередині. Їх навіть іноді називають свіжими фініками – начебто тільки з пальми",
		measure: "500 г",
		price: 120,
		category: "sukhofrukty",
	},
	{
		id: 26,
        src: "./images/sukhofrukty/marmelad_natyral.jpg",
		alt: "marmelad_natyral",
		title: "Мармелад натуральний",
		description: "Мармелад натуральний",
		measure: "500 г",
		price: 295,
		category: "sukhofrukty",
	},
	{
		id: 27,
        src: "./images/sukhofrukty/papai.jpg",
		alt: "papai",
		title: "Папайя",
		description: "Папайя",
		measure: "500 г",
		price: 150,
		category: "sukhofrukty",
	},
	{
		id: 28,
        src: "./images/sukhofrukty/persik.jpg",
		alt: "persik",
		title: "Персик, сушений",
		description: "Персик, сушений",
		measure: "500 г",
		price: 170,
		category: "sukhofrukty",
	},
	{
		id: 29,
        src: "./images/sukhofrukty/cukati_imbir.jpg",
		alt: "cukati_imbir",
		title: "Цукати з імбиру",
		description: "Цукати з імбиру",
		measure: "500 г",
		price: 180,
		category: "sukhofrukty",
	},
	{
		id: 30,
        src: "./images/sukhofrukty/papai_500.jpg",
		alt: "papai",
		title: "Папайя",
		description: "Папайя",
		measure: "500 г",
		price: 250,
		category: "sukhofrukty",
	},
	{
		id: 31,
        src: "./images/sukhofrukty/mango_natural.jpg",
		alt: "mango_natural",
		title: "Манго натуральний сушений Amanti",
		description: "Манго натуральний сушений Amanti",
		measure: "250 г",
		price: 150,
		category: "sukhofrukty",
	},
	{
		id: 32,
        src: "./images/sukhofrukty/mango_natural.jpg",
		alt: "mango_natural",
		title: "Манго натуральний сушений Amanti",
		description: "Манго натуральний сушений Amanti",
		measure: "500 г",
		price: 230,
		category: "sukhofrukty",
	},
	{
		id: 33,
        src: "./images/sukhofrukty/marmelad_delicious.jpg",
		alt: "marmelad_delicious",
		title: "Мармелад турецький",
		description: "Турецький мармелад Delicious готується на основі соку та м'якоті, до якого додається пектин, цукор та лимонна кислота",
		measure: "250 г",
		price: 100,
		category: "sukhofrukty",
	},
	{
		id: 34,
        src: "./images/sukhofrukty/izum_zvichainii.jpg",
		alt: "izum_zvichainii",
		title: "Ізюм звичайний (Іран)",
		description: "Ізюм звичайний<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 150,
		category: "sukhofrukty",
	},
	{
		id: 35,
        src: "./images/sukhofrukty/banana.jpg",
		alt: "banana",
		title: "Бананові чіпси",
		description: "Бананові чіпси<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 250,
		category: "sukhofrukty",
	},
	{
		id: 36,
        src: "./images/sukhofrukty/mango_foot.jpg",
		alt: "mango_foot",
		title: "Манго м'яке сушене",
		description: "Манго м'яке сушене, натуральне, сухофрукти",
		measure: "500 г",
		price: 250,
		category: "sukhofrukty",
	},
	{
		id: 37,
        src: "./images/sukhofrukty/finik_gilka.jpg",
		alt: "finik_gilka",
		title: "Фінік на гілочці",
		description: "Натуральні фініки. М'які та соковиті зберігати лише у холодильнику",
		measure: "1 кг",
		price: 260,
		category: "sukhofrukty",
	},
	{
		id: 38,
        src: "./images/sukhofrukty/izum_dama.jpg",
		alt: "izum_dama",
		title: "Ізюм дамський пальчик синій",
		description: "Ізюм Узбекський дамський пальчик синій<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 350,
		category: "sukhofrukty",
	},
	{
		id: 39,
        src: "./images/sukhofrukty/kyraga_3.jpg",
		alt: "kyraga_3",
		title: "Курага номер 3 (Турція)",
		description: "Курага номер 3<br>(ваговий, від 500 г)",
		measure: "1 кг",
		price: 320,
		category: "sukhofrukty",
	},
];
