export const drink = [
	{
		id: 1,
        src: "./images/drink/kava_standard.jpg",
		alt: "kava_standard",
		title: "Кава мелена Стандарт",
		description: "Чудовий, натуральний німецький кофе, до складу якого входять добірні зерна Арабіки та найкращі боби азіатської Робусті",
		measure: "500 г",
		price: 200,
		category: "drink",
	},
	{
		id: 2,
        src: "./images/drink/kava_lavazza.jpg",
		alt: "kava_lavazza",
		title: "Молота кава Lavazza Quality Oro",
		description: "Склад - 100% арабіка;<br>Ступінь обсмажування - середня;<br>Ступінь помелу - середній помел",
		measure: "250 г",
		price: 190,
		category: "drink",
	},
	{
		id: 3,
        src: "./images/drink/kava_kuru_zerna.jpg",
		alt: "kava_kuru_zerna",
		title: "Кава в зернах KURUKAHVECI (Туреччина)",
		description: "Кава в зернах по-Турецьки, смажена",
		measure: "500 г",
		price: 410,
		category: "drink",
	},
	{
		id: 4,
        src: "./images/drink/kava_espresso.jpg",
		alt: "kava_espresso",
		title: "Кава в зернах ESPRESSO (Туреччина)",
		description: "Кава в зернах ESPRESSO, смажена",
		measure: "500 г",
		price: 450,
		category: "drink",
	},
	{
		id: 5,
        src: "./images/drink/kava_kuru_melena.jpg",
		alt: "kava_kuru_melena",
		title: "Кава мелена KURUKAHVECI (Туреччина)",
		description: "Кава мелена Mehmet Efendi, дрібний помол",
		measure: "100 г",
		price: 90,
		category: "drink",
	},
	{
		id: 6,
        src: "./images/drink/kava_kuru_melena_500.jpg",
		alt: "kava_kuru_melena_500",
		title: "Кава мелена KURUKAHVECI (Туреччина)",
		description: "Кава мелена Mehmet Efendi, дрібний помол",
		measure: "500 г",
		price: 450,
		category: "drink",
	},
	{
		id: 7,
        src: "./images/drink/kava_kuru_melena_250.jpg",
		alt: "kava_kuru_melena_250",
		title: "Кава мелена KURUKAHVECI (Туреччина)",
		description: "Кава мелена Mehmet Efendi, дрібний помол",
		measure: "250 г",
		price: 250,
		category: "drink",
	},
	{
		id: 8,
        src: "./images/drink/tea_klassik.jpg",
		alt: "tea_klassik",
		title: "Зелений чай Gruner Tee Klassik (Німеччина)",
		description: "Грюнер Ті Класік - натуральний смак чайного листя без ароматизаторів та смакових добавок",
		measure: "250 г",
		price: 190,
		category: "drink",
	},
	{
		id: 9,
        src: "./images/drink/tea_zitrone.jpg",
		alt: "tea_zitrone",
		title: "Чай зелений Gruner Tee Zitrone (Німеччина)",
		description: "Освіжаючий цитрусовий аромат, багатий на вітаміни і мікроелементи, сильний антиоксидант",
		measure: "250 г",
		price: 190,
		category: "drink",
	},
	{
		id: 10,
        src: "./images/drink/tea_schwarzer.jpg",
		alt: "tea_schwarzer",
		title: "Чай чорний Ostfriesische Teemischung (Німеччина)",
		description: "Чудово тонізує та надає бадьорості всьому тілу. Терпкий чорний чай, має насичений смак та колір",
		measure: "250 г",
		price: 170,
		category: "drink",
	},
	{
		id: 11,
        src: "./images/drink/tea.jpg",
		alt: "tea",
		title: "Чорний чай",
		description: "Полуниця з вершками<br>Султан Сулейман",
		measure: "400 г",
		price: 250,
		category: "drink",
	},
	{
		id: 12,
        src: "./images/drink/kakao.jpg",
		alt: "kakao",
		title: "Какао Kurukahveci Mehmet Efendi (Туреччина)",
		description: "Какао має вишуканий тонкий аромат і густий смак, насичений пряними та солодкуватими відтінками",
		measure: "250 г",
		price: 230,
		category: "drink",
	},
	{
		id: 13,
        src: "./images/drink/choko.jpg",
		alt: "choko",
		title: "Гарячий шоколад Torras Sabor Tradicional (Іспанія)",
		description: "Солодкий, густий і поживний<br>Низький вміст жиру, без глютену",
		measure: "360 г",
		price: 140,
		category: "drink",
	},
];
