export const rahat = [
	{
		id: 1,
        src: "./images/rahat/rahat_16.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Асорті східних солодощів",
		measure: "1 кг",
		price: 200,
		category: "rahat",
	},
	{
		id: 2,
        src: "./images/rahat/rahat_2.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "1,5 кг",
		price: 210,
		category: "rahat",
	},
	{
		id: 3,
        src: "./images/rahat/rahat_3.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "1,5 кг",
		price: 210,
		category: "rahat",
	},
	{
		id: 4,
        src: "./images/rahat/rahat_4.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "1,5 кг",
		price: 210,
		category: "rahat",
	},
	{
		id: 5,
        src: "./images/rahat/rahat_5.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум",
		measure: "1,5 кг",
		price: 210,
		category: "rahat",
	},
	{
		id: 6,
        src: "./images/rahat/rahat_17.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Асорті східних солодощів (Туреччина)",
		measure: "1 кг",
		price: 350,
		category: "rahat",
	},
	{
		id: 7,
        src: "./images/rahat/rahat_7.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум, з горіхом",
		measure: "1,5 кг",
		price: 210,
		category: "rahat",
	},
	{
		id: 8,
        src: "./images/rahat/rahat_8.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум, з горіхом",
		measure: "2 кг",
		price: 250,
		category: "rahat",
	},
	{
		id: 9,
        src: "./images/rahat/rahat_9.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум - це давня східна насолода. Складається з фруктового соку, крохмалю, цукру та арахісу.<br>Смак граната, абрикос, ківі та ванілі",
		measure: "1,5 кг",
		price: 200,
		category: "rahat",
	},
	{
		id: 10,
        src: "./images/rahat/rahat_18.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум (Туреччина)",
		measure: "500 гр",
		price: 240,
		category: "rahat",
	},
	{
		id: 11,
        src: "./images/rahat/rahat_19.jpg",
		alt: "rahat",
		title: "Рахат-Лукум (Туреччина)",
		description: "● зі смаком гранату та фісташками<br>● з фісташками<br>● з інжиром та волоським горіхом<br>● асорті",
		measure: "400 гр",
		price: 210,
		category: "rahat",
	},
	{
		id: 12,
        src: "./images/rahat/rahat_12.jpg",
		alt: "rahat",
		title: "Рахат-Лукум",
		description: "Рахат-Лукум, фруктовий",
		measure: "1,5 кг",
		price: 200,
		category: "rahat",
	},
];
